# Data Factory, landing only (PRD §3 v1.4): scheduled HTTP-to-ADLS copies of raw
# BTS/IEM files. No dataflows, no transform activities — Dagster is the control
# plane and Databricks does the transforms. Custom (JSON) linked services and
# datasets are used throughout: the typed azurerm dataset resources don't cover
# the HttpServer-to-BlobFS binary pairing.

resource "azurerm_data_factory" "this" {
  name                = "skynyc-adf"
  location            = azurerm_resource_group.this.location
  resource_group_name = azurerm_resource_group.this.name
}

# TranStats' certificate chain is served incomplete; validation stays off for this
# one host (public, unauthenticated data — integrity is enforced by row counts and
# schema checks downstream, not transport).
resource "azurerm_data_factory_linked_custom_service" "http_transtats" {
  name            = "ls_http_transtats"
  data_factory_id = azurerm_data_factory.this.id
  type            = "HttpServer"
  type_properties_json = jsonencode({
    url                               = "https://transtats.bts.gov"
    authenticationType                = "Anonymous"
    enableServerCertificateValidation = false
  })
}

resource "azurerm_data_factory_linked_custom_service" "http_iem" {
  name            = "ls_http_iem"
  data_factory_id = azurerm_data_factory.this.id
  type            = "HttpServer"
  type_properties_json = jsonencode({
    url                               = "https://mesonet.agron.iastate.edu"
    authenticationType                = "Anonymous"
    enableServerCertificateValidation = true
  })
}

resource "azurerm_data_factory_linked_custom_service" "adls" {
  name            = "ls_adls"
  data_factory_id = azurerm_data_factory.this.id
  type            = "AzureBlobFS"
  type_properties_json = jsonencode({
    url        = "https://${var.storage_account_name}.dfs.core.windows.net"
    accountKey = { type = "SecureString", value = var.storage_key }
  })
}

resource "azurerm_data_factory_custom_dataset" "http_bts" {
  name            = "ds_http_bts"
  data_factory_id = azurerm_data_factory.this.id
  type            = "Binary"
  linked_service { name = azurerm_data_factory_linked_custom_service.http_transtats.name }
  parameters      = { relativeUrl = "" }
  type_properties_json = jsonencode({
    location = { type = "HttpServerLocation", relativeUrl = "@dataset().relativeUrl" }
  })
}

resource "azurerm_data_factory_custom_dataset" "http_iem" {
  name            = "ds_http_iem"
  data_factory_id = azurerm_data_factory.this.id
  type            = "Binary"
  linked_service { name = azurerm_data_factory_linked_custom_service.http_iem.name }
  parameters      = { relativeUrl = "" }
  type_properties_json = jsonencode({
    location = { type = "HttpServerLocation", relativeUrl = "@dataset().relativeUrl" }
  })
}

resource "azurerm_data_factory_custom_dataset" "adls_binary" {
  name            = "ds_adls_binary"
  data_factory_id = azurerm_data_factory.this.id
  type            = "Binary"
  linked_service { name = azurerm_data_factory_linked_custom_service.adls.name }
  parameters      = { dir = "", file = "" }
  type_properties_json = jsonencode({
    location = {
      type       = "AzureBlobFSLocation"
      fileSystem = "raw"
      folderPath = "@dataset().dir"
      fileName   = "@dataset().file"
    }
  })
}

locals {
  copy_policy = { timeout = "0.02:00:00", retry = 2, retryIntervalInSeconds = 60 }

  bts_copy_activity = {
    name   = "copy_bts_month"
    type   = "Copy"
    policy = local.copy_policy
    inputs = [{
      referenceName = "ds_http_bts", type = "DatasetReference"
      parameters = { relativeUrl = "@concat('PREZIP/On_Time_Reporting_Carrier_On_Time_Performance_1987_present_', item().y, '_', item().m, '.zip')" }
    }]
    outputs = [{
      referenceName = "ds_adls_binary", type = "DatasetReference"
      parameters = {
        dir  = "@concat('bts/ym=', item().ym)"
        file = "@concat('ontime_', item().ym, '.zip')"
      }
    }]
    typeProperties = {
      source = { type = "BinarySource", storeSettings = { type = "HttpReadSettings", requestMethod = "GET" } }
      sink   = { type = "BinarySink", storeSettings = { type = "AzureBlobFSWriteSettings" } }
    }
  }
}

# Backfill pipeline: caller supplies the month list (generated by
# scripts/gen_backfill_params.py — ~470 entries for Oct 1987 through the
# freshest published month).
resource "azurerm_data_factory_pipeline" "land_bts" {
  name            = "pl_land_bts"
  data_factory_id = azurerm_data_factory.this.id
  # azurerm exposes string-typed pipeline parameters only, so the month list
  # travels as a JSON string and ForEach parses it with @json().
  parameters      = { ymList = "[]" }
  activities_json = jsonencode([{
    name = "for_each_month"
    type = "ForEach"
    typeProperties = {
      items       = { value = "@json(pipeline().parameters.ymList)", type = "Expression" }
      isSequential = false
      batchCount   = 8
      activities   = [local.bts_copy_activity]
    }
  }])
}

# Incremental pipeline for the monthly trigger: lands the month published ~3 months
# back (2-month reporting lag + safety). Idempotent — re-landing overwrites the
# same path.
resource "azurerm_data_factory_pipeline" "land_bts_latest" {
  name            = "pl_land_bts_latest"
  data_factory_id = azurerm_data_factory.this.id
  activities_json = jsonencode([{
    name   = "copy_latest_month"
    type   = "Copy"
    policy = local.copy_policy
    inputs = [{
      referenceName = "ds_http_bts", type = "DatasetReference"
      parameters = { relativeUrl = "@concat('PREZIP/On_Time_Reporting_Carrier_On_Time_Performance_1987_present_', formatDateTime(adddays(utcnow(), -90), 'yyyy'), '_', formatDateTime(adddays(utcnow(), -90), '%M'), '.zip')" }
    }]
    outputs = [{
      referenceName = "ds_adls_binary", type = "DatasetReference"
      parameters = {
        dir  = "@concat('bts/ym=', formatDateTime(adddays(utcnow(), -90), 'yyyy-MM'))"
        file = "@concat('ontime_', formatDateTime(adddays(utcnow(), -90), 'yyyy-MM'), '.zip')"
      }
    }]
    typeProperties = {
      source = { type = "BinarySource", storeSettings = { type = "HttpReadSettings", requestMethod = "GET" } }
      sink   = { type = "BinarySink", storeSettings = { type = "AzureBlobFSWriteSettings" } }
    }
  }])
}

# IEM pull, chunked per station-decade — one 39-year request per station would
# lean on the archive server harder than their usage guidance likes.
resource "azurerm_data_factory_pipeline" "land_iem" {
  name            = "pl_land_iem"
  data_factory_id = azurerm_data_factory.this.id
  parameters      = { chunks = "[]" }
  activities_json = jsonencode([{
    name = "for_each_chunk"
    type = "ForEach"
    typeProperties = {
      items       = { value = "@json(pipeline().parameters.chunks)", type = "Expression" }
      isSequential = false
      batchCount   = 3
      activities = [{
        name   = "copy_iem_chunk"
        type   = "Copy"
        policy = local.copy_policy
        inputs = [{
          referenceName = "ds_http_iem", type = "DatasetReference"
          parameters = { relativeUrl = "@concat('cgi-bin/request/asos.py?station=', item().station, '&data=all&year1=', item().y1, '&month1=1&day1=1&year2=', item().y2, '&month2=12&day2=31&tz=Etc%2FUTC&format=onlycomma&latlon=no&missing=M&trace=T')" }
        }]
        outputs = [{
          referenceName = "ds_adls_binary", type = "DatasetReference"
          parameters = {
            dir  = "@concat('iem/station=K', item().station)"
            file = "@concat('asos_', item().y1, '_', item().y2, '.csv')"
          }
        }]
        typeProperties = {
          source = { type = "BinarySource", storeSettings = { type = "HttpReadSettings", requestMethod = "GET" } }
          sink   = { type = "BinarySink", storeSettings = { type = "AzureBlobFSWriteSettings" } }
        }
      }]
    }
  }])
}

# Ships deactivated — project convention (same as Dagster schedules): automation
# is toggled on deliberately, never by default.
resource "azurerm_data_factory_trigger_schedule" "monthly" {
  name            = "trg_monthly_bts"
  data_factory_id = azurerm_data_factory.this.id
  pipeline_name   = azurerm_data_factory_pipeline.land_bts_latest.name
  interval        = 1
  frequency       = "Month"
  activated       = false
  schedule {
    days_of_month = [5]
    hours         = [6]
    minutes       = [0]
  }
}
